# Cloud Build configuration file for event-processor

substitutions:
  _SOURCE_BUCKET: event-data-raw
  _SUMMARY_BUCKET: event-data-summary
  _BIGQUERY_DATASET: platform_event_data
  _BIGQUERY_TABLE: event_hourly_summary
  _BIGQUERY_STG_TABLE: event_hourly_summary_staging
  _HOURS_THRESHOLD: "24"
  _REPO_NAME: event-processor-repo

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Run unit tests
  - name: 'python:3.9-slim'
    id: 'Unit Tests'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt
        python -m pytest test_main.py -v

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: "Build"
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/event-processor:$TAG_NAME'
      - '.'

  # Step 3: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/event-processor:$TAG_NAME'

  # Deploy Cloud Run job
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-job'
    entrypoint: gcloud
    args:
      - 'run'
      - 'jobs'
      - 'create'
      - 'event-processor-job'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/event-processor:$TAG_NAME'
      - '--region=us-central1'
      - '--cpu=1'
      - '--memory=2Gi'
      - '--max-retries=3'
      - '--task-timeout=3600s'
      - '--set-env-vars=SOURCE_BUCKET=$_SOURCE_BUCKET,SUMMARY_BUCKET=$_SUMMARY_BUCKET,BIGQUERY_DATASET=$_BIGQUERY_DATASET,BIGQUERY_TABLE=$_BIGQUERY_TABLE,BIGQUERY_STG_TABLE=$_BIGQUERY_STG_TABLE,HOURS_THRESHOLD=$_HOURS_THRESHOLD'

# Use Container Registry to store the image
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/event-processor:$TAG_NAME'

# Timeout for the entire build process
timeout: '1800s'  # 30 minutes